projects:
  todolist:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: w6x7jbytknhqzcbd4gu3qbmt3y
      endpoints:
        prod: >-
          https://f7efhg75bfc2pdxfyri52dnarm.appsync-api.ap-northeast-1.amazonaws.com/graphql
