projects:
  todolist:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: erfkn44fivhytpozmaw6spl7sy
      endpoints:
        prod: >-
          https://uctbf7dexnh7hkke6v2cjep3ee.appsync-api.ap-northeast-1.amazonaws.com/graphql
