name: draft

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  check:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - id: nodenv
        uses: nodenv/actions/node-version@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nodenv.outputs.node-version }}

      - uses: bahmutov/npm-install@v1

      - run: yarn lint
      - run: yarn test

      - run: yarn build
      - uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: './out'
          production-branch: master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
