name: draft

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  check:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - id: nodenv
        uses: nodenv/actions/node-version@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ steps.nodenv.outputs.node-version }}

      - uses: actions/cache@v2.1.7
        with:
          path: .yarn/cache
          key: app-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            app-yarn-${{ hashFiles('yarn.lock') }}
            app-yarn-
      - run: yarn

      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: './out'
          production-branch: master
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
