name: production

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - id: nodenv
        uses: nodenv/actions/node-version@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nodenv.outputs.node-version }}

      - id: node_modules
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: app-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: app-yarn-${{ hashFiles('yarn.lock') }}

      - run: yarn
        if: steps.node_modules.outputs.cache-hit != 'true'

      - run: yarn lint
      - run: yarn test

      - run: yarn build
      - uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: './out'
          production-branch: master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}